version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:9-jdk
    steps:
      - checkout
      - run:
          name: Run integration tests
          command: ./mvnw verify -Dit.http.skip.fileTransfer=true
          environment:
            MAVEN_OPTS: -Xms256m -Xmx2048m

