version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:9-jdk
    steps:
      - checkout
      - run:
          name: Run integration tests
          command: ./mvnw verify -Dit.http.skip.fileTransfer=true -e
          environment:
            MAVEN_OPTS: -Xms128m -Xmx1024m

